Select FIRST_HALF.FLAVOR
From FIRST_HALF, ICECREAM_INFO
Where FIRST_HALF.TOTAL_ORDER >=3000 AND ICECREAM_INFO.INGREDIENT_TYPE='fruit_based' AND FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
Order by FIRST_HALF.TOTAL_ORDER DESC;