# FOMC 
## PROP TRADER ##

Select INGREDIENT_TYPE, Sum(TOTAL_ORDER) AS INGREDIENT_TYPE
From FIRST_HALF, ICECREAM_INFO
Where FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
Group by ICECREAM_INFO.INGREDIENT_TYPE
Order by TOTAL_ORDER ASC;