Select r.FOOD_TYPE, r.REST_ID, r.REST_NAME, r.FAVORITES
From REST_INFO r
Join (Select FOOD_TYPE, MAX(FAVORITES) AS MAX_FAV
      From REST_INFO
      Group by FOOD_TYPE) m 
On r.FOOD_TYPE = m.FOOD_TYPE AND r.FAVORITES = m.MAX_FAV
Order by FOOD_TYPE DESC;